[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "script-src 'self' *.googletagmanager.com *.adobedtm.com *.trustarc.com *.weglot.com *.sitebay.org 'unsafe-eval' 'unsafe-inline'"

[[headers]]
for = "/**.{css,jpg,js}"

[headers.values]
Cache-Control = "public, max-age=2"

[[redirects]]
from = "/support/blog/**"
to = "/support/sections/"
status = 200

[[redirects]]
from = "/support/marketplace/**"
to = "/support/sections/"
status = 200

[[redirects]]
from = "/support/resources/**"
to = "/support/sections/"
status = 200