#!/bin/bash

# Usage:
#     OBJ_ACCESS_KEY=<an OBJ access key> OBJ_SECRET_KEY=<an OBJ secret key> DEPLOY_SUFFIX=-suffix-for-obj-bucket-name ./deploy_to_object_storage.sh
#
# This script builds the site into `public/`, and then syncs the contents of that
# folder to the `/support/` directory of an object storage bucket.
#
# The name of the bucket will be of the form `sitebaydocsprod/support`, where
# `DEPLOY_SUFFIX` is passed as an environment variable.
# For example, setting `DEPLOY_SUFFIX=-latestrelease` will deploy to our production
# Object Point-in-Time Machine bucket, which is `sitebaydocs-latestrelease`, in the us-east cluster.
#
# Lastly, it calls the `generate_permanent_redirects.sh` script to set 301 redirects
# for each page generated by Hugo's `aliases` frontmatter.
#
# A future iteration of this will use Terraform to create the bucket if it doesn't
# exist already. Until then, you will need to create the bucket ahead of time.

cd ..
rm -rf public/
hugo

# Configure the bucket as a website, just in case it isn't already
#s3cmd  ws-create --ws-index=index.html --ws-error=404.html s3://sitebaydocsprod.sitebay.ca

# Sync these first, but don't delete the previous files, because there will be pages that rely on them
#s3cmd  --no-mime-magic --acl-public sync public/css/ s3://sitebaydocsprod/support/css/
#s3cmd  --no-mime-magic --acl-public sync public/js/ s3://sitebaydocsprod/support/js/
#s3cmd  --no-mime-magic --acl-public sync public/jslibs/ s3://sitebaydocsprod/support/jslibs/
#s3cmd  --no-mime-magic --acl-public sync public/images/ s3://sitebaydocsprod/support/images/

# Sync the other pages
s3cmd --no-mime-magic --acl-public sync public/ s3://sitebaydocsprod.sitebay.ca/support/ --no-check-certificate

# Generate the 301 permanent redirectscd scripts
cd scripts
./generate_permanent_redirects.sh
